---
- name: Template-driven switch port change
  hosts: "{{ target_hosts }}"
  gather_facts: no

  vars:
    vlan_id: "{{ vlan_id }}"
    int_id: "{{ int_id }}"
    user_name: "{{ user_name }}"
    int_desc: "{{ int_desc }}"

  tasks:
    - name: Configure templates per OS
      include_tasks: "{{ item }}"
      with_first_found:
        - "{{ playbook_dir }}/tasks/{{ ansible_network_os }}.yml"
        - "{{ playbook_dir }}/tasks/unsupported.yml"

